pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               bat 'start pepega.png'
               bat 'start pepa.jpg'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..!!'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....!!'
            }
        }
    }
}