pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'cd C:\Users\Anton_Markov1\Desktop\MAY DAY && start pepega.png'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..!!'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....!!'
            }
        }
    }
}